---
# tasks file for dallenjs
- name: Ensure group "app" exists
  group:
    name: app
    state: present

- name: Add user "app"  
  user:
    name: app
    groups: app
    shell: /bin/bash
    home: /srv/app
    comment: "App run user"
    state: present
    password: '!'

- name: Ensure nginx is installed
  apt:
    name: nginx
    update_cache: yes
    state: latest

- name: Setup nginx config
  template:
    src: templates/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'

- name: Install MySQL
  apt: 
    name: ['python-mysqldb', 'mysql-server']
    update_cache: yes
    cache_valid_time: 3600 
    state: present

- name: Start the MySQL service
  service:
    name: mysql 
    state: started
    enabled: true

- name: update mysql root password for all root accounts
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Ensure curl and wget are installed
  apt:
    name: 
      - curl
      - wget
    update_cache: yes
    state: latest

- name: install NVM
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | /bin/bash
  args:
    creates: "/srv/app/.nvm/nvm.sh"
  become: yes
  become_user: app

- name: install node 10 lts
  shell: >
    source ~/.nvm/nvm.sh && nvm install 10 && nvm alias default 10
  args:
    executable: /bin/bash
    creates: "/srv/app/.nvm/alias"
  become: yes
  become_user: app

- name: Ensure git is installed
  apt:
    name: git
    update_cache: yes
    state: latest

- name: download dallen-js repo
  git:
    repo: https://github.com/DonoA/DallenJS.git
    dest: ~/DallenJS
    force: yes
  become: yes
  become_user: app

- name: build server
  shell: >
    source ~/.nvm/nvm.sh && ./build.sh
  args:
    chdir: ~/DallenJS
    executable: /bin/bash
  become: yes
  become_user: app

- name: create nginx config
  template:
    src: templates/nginx/dallenjs.conf.j2
    dest: /etc/nginx/sites-available/dallenjs.conf
    owner: root
    group: root
    mode: '0644'

- name: link nginx config
  file:
    src: /etc/nginx/sites-available/dallenjs.conf
    dest: /etc/nginx/sites-enabled/dallenjs.conf
    owner: root
    group: root
    state: link

- name: create server config
  template:
    src: templates/config.json.j2
    dest: /srv/app/DallenJS/server/config.json
    owner: app
    group: app
    mode: '0644'

- name: create db setup script
  template:
    src: templates/setup_db.sql.j2
    dest: /srv/app/DallenJS/server/setup_db.sql
    owner: app
    group: app
    mode: '0644'

- name: Run mysql setup file
  mysql_db:
    state: import
    name: all
    login_user: root
    login_password: "{{ mysql_root_password }}"
    target: /srv/app/DallenJS/server/setup_db.sql

- name: create database.json file
  template:
    src: templates/database.json.j2
    dest: /srv/app/DallenJS/server/database.json
    owner: app
    group: app
    mode: '0644'

- name: run database migrations
  shell: >
    source ~/.nvm/nvm.sh && npm run migrate up
  args:
    chdir: /srv/app/DallenJS/server
    executable: /bin/bash
  become: yes
  become_user: app

- name: create dallenjs service
  template:
    src: templates/dallenjs.service.j2
    dest: /lib/systemd/system/dallenjs.service
    owner: app
    group: app
    mode: '0644'